### ISSUE TITLE
SEO to the application

### ISSUE THREAD

**Issue by imarunkumar** [open-template-hub/company-profile-ui-template#269]
In SEO perspective how to achieve using this template How to do SSR in this application,
For example :
I run the command ng build when i deploy it in server still not rendering the entire content it showing only the <app-root>
Can u help on this?

**Comment by fatihturker** [comment]
Hi @imarunkumar ,

SSR implementation is in progress now, here you can find the branch:
https://github.com/open-template-hub/company-profile-ui-template/tree/major/ssr

Feel free to contribute and use.

Best Regards,
Fatih
